### ISSUE TITLE
It works but ...

### ISSUE THREAD

**Issue by Nex4rius** [ps-wow/OPie_Classic#1]
<img src="https://i.imgur.com/80jLtD6.png"><img src="https://i.imgur.com/ohmiFKV.png">

**Comment by davidcraig** [comment]
That's interesting, I haven't seen that happen, what is on the ring, and does it only happen under certain circumstances?

**Comment by Nex4rius** [comment]
That's strange. It happend when I first instaled it but now after restarting wow it's working normally :)

**Comment by davidcraig** [comment]
It might have been if you copied the folder over the top while wow was open maybe /shrug
